// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4B84iIBio6J9mc53Gy_VKwisN1xbRsxY',
    appId: '1:3501013568:web:d6effba242ed5174683da5',
    messagingSenderId: '3501013568',
    projectId: 'bdnote-9f723',
    authDomain: 'bdnote-9f723.firebaseapp.com',
    databaseURL: 'https://bdnote-9f723-default-rtdb.firebaseio.com',
    storageBucket: 'bdnote-9f723.appspot.com',
    measurementId: 'G-37QB9NL8FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuYHT0D4fcG0HYQIr-9ppy4JEotsbLank',
    appId: '1:3501013568:android:d0d9bea76d389216683da5',
    messagingSenderId: '3501013568',
    projectId: 'bdnote-9f723',
    databaseURL: 'https://bdnote-9f723-default-rtdb.firebaseio.com',
    storageBucket: 'bdnote-9f723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVpGD8sdDNGugCuk_KQIY6aKKIfoG01c',
    appId: '1:3501013568:ios:4069ad20910cf25f683da5',
    messagingSenderId: '3501013568',
    projectId: 'bdnote-9f723',
    databaseURL: 'https://bdnote-9f723-default-rtdb.firebaseio.com',
    storageBucket: 'bdnote-9f723.appspot.com',
    iosClientId: '3501013568-df74opun7u3775je8vjg9jn57umfjnfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nota',
  );
}
